<?xml version="1.0" encoding="UTF-8"?><!--декларация (пролог + кодировка)-->
<?xml-stylesheet type="text/css" href="1.css"?><!--подключение файла таблицы стилей и самого css файла-->
<!DOCTYPE INVENTORY [ <!--декларация DOCTYPE является ссылкой на внешний файл определений типов документа-->
    <!ELEMENT INVENTORY ((UNIVERSITY)+,NAME, BALL, KOL, TOWN)>
    <!ELEMENT UNIVERSITY (#PCDATA)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT BALL (#PCDATA)>
    <!ELEMENT KOL (#PCDATA)>
    <!ELEMENT TOWN (#PCDATA)>
]>
<INVENTORY>
    <UNIVERSITY>
      <NAME>БГТУ</NAME>
	    <BALL>305 баллов</BALL>
      <KOL>40 человек</KOL>
      <TOWN>г.Минск</TOWN>
    </UNIVERSITY>
    <UNIVERSITY>
      <NAME>БГУ</NAME>
      <BALL>333 баллов</BALL>
      <KOL>35 человек</KOL>
      <TOWN>г.Минск</TOWN>
    </UNIVERSITY>
    <UNIVERSITY>
      <NAME>БНТУ</NAME>
      <BALL>300 баллов</BALL>
      <KOL>45 человек</KOL>
      <TOWN>г.Минск</TOWN>
    </UNIVERSITY>
    <UNIVERSITY>
      <NAME>БрГТУ</NAME>
      <BALL>297 баллов</BALL>
      <KOL>20 человек</KOL>
      <TOWN>г.Брест</TOWN>
    </UNIVERSITY>
</INVENTORY>


