=== Kohnyusha/OIT-1-kurs-2/XML/Лабораторная № 2/sch2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> <!--указывает, что элементы и типы данных, используемые в схеме, происходят из этого пространства имен, также они должны иметь префикс xs-->
    <xs:element name = "CARTOON"><!--определяет элемент-->
        <xs:complexType><!--у элемента комплексный тип-->
            <xs:sequence><!--комплексный тип – эпоследовательность элементов-->
                <xs:element name = "NAME" type = "xs:string"/>
                <xs:element name = "YEAR" type = "xs:string"/>
                <xs:element name = "ZHANR" type = "xs:string"/>
                <xs:element name = "REITING" type = "xs:string"/>
                <xs:element name = "FILM" type = "xs:string"/>
            </xs:sequence>
        </xs:complexType> 
    </xs:element> 
</xs:schema>

=== Kohnyusha/OIT-1-kurs-2/XML/Лабораторная № 2/l2 (2стр schema).xml
<?xml version="1.0" encoding="UTF-8"?><!--декларация (пролог + кодировка)-->
 <?xml-stylesheet type="text/css" href="2.css"?>
 <CARTOON xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation = "sch2.xsd"> <!--указывает, что элементы и типы данных, используемые в схеме, происходят из этого пространства имен, также они должны иметь префикс xs-->
<FILM>
      <NAME>Rick and Morty</NAME>
      <YEAR>4 декабря 2013 г.</YEAR>
      <ZHANR>Жанр: мультфильм, комедия, фантастика, приключения</ZHANR>
      <REITING>КиноПоиск 8,9 из 10</REITING>
</FILM>
<FILM>
      <NAME>Gravity Falls</NAME>
      <YEAR>4 января 2013 г.</YEAR>
      <ZHANR>Жанр: мультфильм, комедия, детектив, приключения, семейный, фантастика</ZHANR>
      <REITING>КиноПоиск 8,9 из 10</REITING>
</FILM>
<FILM>
      <NAME>Phineas and Ferb</NAME>
      <YEAR>10 августа 2010 г.</YEAR>
      <ZHANR>Жанр: семейный, комедия, боевик, фантастика, мультфильм, короткометражка</ZHANR>
      <REITING>КиноПоиск 7,4 из 10</REITING>
</FILM>
 </CARTOON>
